### ISSUE TITLE
The !primo command is broke

### ISSUE THREAD

**Issue by Juliaria08** [makigas/clank#140]
**Describe the bug**
When you make use of the !primo command it can be broked

**To Reproduce**
Send the message !primo Text`outcuote

**Expected behavior**
Put the ` charter by first putting a backslash

**Screenshots**
![image](https://user-images.githubusercontent.com/54623995/83754522-620e3b00-a66c-11ea-9cd6-950e1890256d.png)

**Additional context**
Its on the server [Message](https://discordapp.com/channels/329487017916366850/448199629448675329/718071955734921288)

**Comment by Juliaria08** [comment]
@danirod Sorry for the mispell i used gogle translade and it have a good problem

**Comment by danirod** [comment]
Sure, it is a legit and understandable confusion, but it is clearly not the same a prime number and a cousin number ;)

Enviado desde mi iPad

**Comment by Juliaria08** [comment]
> Sure, it is a legit and understandable confusion, but it is clearly not the same a prime number and a cousin number ;) Enviado desde mi iPad
> […](#)
> El 7 jun 2020, a las 17:02, Julian Marcos ***@***.***> escribió: ﻿ @danirod Sorry for the mispell i used gogle translade and it have a good problem — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes for the translade tanks is wat im thinking
