### ISSUE TITLE
If a user gets warned he manualy can delete themselves warn

### ISSUE THREAD

**Issue by Juliaria08** [makigas/clank#152]
**Describe the bug**
Discord if you left a server your roles get reset and if a user lefts it can get back on the server verificate and isnt warned

**To Reproduce**
As an administrator warn a account you own and left the server and then go back into the server with an invite link
you have veen reseted the roles. If the server has a verification role verify yourself and you are no longer warned

**Expected behavior**
The bot add the warned role back

**Comment by danirod** [comment]
That is the expected behaviour. Users caught doing this or rejoining to circumvent a kick will receive a ban.

**Comment by Juliaria08** [comment]
Ok
