### ISSUE TITLE
El automute asume mi género

### ISSUE THREAD

**Issue by danirod** [makigas/clank#455]
Reescribir mensaje de aviso en castellano neutro:
https://github.com/makigas/clank/blob/77e2e04abf3462f7d17c000718cbb4af7c8df615/src/hooks/karma.ts#L166

**Comment by danirod** [comment]
This doesn't happen anymore because the message has been changed.

**Comment by owlnai** [comment]
Fixed in https://github.com/makigas/makibot/commit/ed13e8839915c55e717ece1fac9c0c2ccbf3d1d8#
