### ISSUE TITLE
Makibot no permite a los mods hace moderacion de los hilos

### ISSUE THREAD

**Issue by xaviermazon** [makigas/clank#503]
**Describe the bug**
Un moderador no puede archivar un hilo

**To Reproduce**
Lanzar /achivar siendo moderador

**Expected behavior**
Que puediese archivar porque es moderador

**Screenshots**
![imagen](https://user-images.githubusercontent.com/16853169/154524484-838b2029-501a-41df-b929-787523c59bc9.png)

**Additional context**
Matiuri no quiere hacer ni Issue y ni PR, asi que le hago el favor

**Comment by danirod** [comment]
Fixed, thank you.
