### ISSUE TITLE
Mostrar un mensaje mas claro sobre el Throw causado por Login

### ISSUE THREAD

**Issue by dannywolfmx** [makigas/clank#513]
Actualmente al realizar loggin, si este no logra hacerlo de forma satisfactoria, el sistema  muestra toda la traza de error, causando que no se ajuste a la estática del "cli". 

Discord.js cuenta con la posibilidad de obtener el código del error y este por lo visto retorna es lo suficientemente descriptivo para lograr saber cual fue el error en cuestión. Por ejemplo si el token es invalido el código obtenido es "TOKEN_INVALID"

https://discordjs.guide/popular-topics/errors.html#code

Antes:
![image](https://user-images.githubusercontent.com/1672871/155891578-9308be44-ccae-4e92-a7ca-2002112910bc.png)

Despues: 
![image](https://user-images.githubusercontent.com/1672871/155891552-70e8ef03-051d-4dce-a3fc-be5719dc5571.png)

**Comment by danirod** [comment]
Ah, entiendo. Antes en #512 puse la keyword de error como un comment porque no encontré cómo acceder al objeto APIErrors, aunque igual es cosa de TypeScript. Pero si existe lo tendré en cuenta.

Faltan muchos try-catch, indudablemente. Me entero de los que faltan porque me avisa Sentry cuando se produce un error no capturado.

**Comment by dannywolfmx** [comment]
En relación a #512 y el "DISALLOWED_INTENTS" estoy viendo y en apiErrors no esta este error, pero esta en un objeto llamado WSCodes.

Quizás se pueda hacer algo como WSCodes[error.code] y obtener información, pero creo que es demasiado esfuerzo para una  un método puntual.

Eso sí, si el el "error.code" no es de tipo WSCodes entonces este mostrara a pantalla solo un numero sin texto, pero supongo que esta bien.

Meh, sera cuestion de ver.
