### ISSUE TITLE
No eliminar los enlaces duplicados

### ISSUE THREAD

**Issue by xaviermazon** [makigas/clank#524]
**Describe the bug**
El bot no elimina los enlaces duplicados en el canal de enlaces

**To Reproduce**
Poner un enlace 2 veces en el canal de enlaces

**Expected behavior**
Que eliminase el post duplicado

**Screenshots**
![Issue de enlaces](https://user-images.githubusercontent.com/16853169/158574112-307aa50d-65a0-473d-9b12-41fdb7abd1b5.png)

**Additional context**

**Comment by danirod** [comment]
Tengo que ser convencido de que esto sea realmente un bug. El antiflood eliminaría el mensaje si lo mandases muy de seguido, pero compartir un enlace que se pasó un par de días antes tampoco es algo que no se permita en otros sitios como Reddit o Hacker News... ya es la gente quien se ocupa de recordar en el hilo que es un dupe.

**Comment by xaviermazon** [comment]
Si ves que realmente no es bug cierra el issue, yo considero que no funciona

**Comment by danirod** [comment]
Lo voy a cerrar por limitaciones técnicas de cara a comprobar en el historial que no sea repetido, dado que la API de Discord tampoco parece rechazar dos hilos llamados iguales.
