### ISSUE TITLE
Keep inactive timestamp records for verified GuildMembers

### ISSUE THREAD

**Issue by danirod** [makigas/clank#9]
Because verified users have already got a role, Discord's prune tool will not include them when pruning inactive users, which is something that every few months I do for users that haven't logged in, in a long time.

The reason I prune inactive users is that it provides a skewed statistic over the amount of users the server has. Plus, you never know when an inactive account may become a zombie account: it gets compromised and a bad actor uses it to send malware or spam.

The bot should log the last time an user goes available or unavailable in order to remove the verified badge, or at least mark the user as inactive, if the user has not logged in in three months.

**Comment by Juliaria08** [comment]
It can ve solved via putting the discord server on purne security on "Scan media content from all members"
